theme: jekyll-theme-cayman
title: R Consortium Working Group Template
description: >
  This site is provided as a template for R Consortium Working Groups. Please edit this
  description with a short overview of the Working Group.
show_downloads: false

